### PR TITLE
Add support for ARM64 (Apple Silicon / M1)

### LINKED ISSUE #5: Plugin fails to install on M1/Apple Silicon macs
The plugin fails to install on macs with the newer Apple Silicon (M1) which is ARM64 rather than intel architecture.

Is it possible for you to add `darwin/arm64` as one of the build outputs?

```
kubectl krew install sick-pods
Updated the local copy of plugin index.
Updated the local copy of plugin index "kvaps".
Installing plugin: sick-pods
W0829 14:04:43.859011   12900 install.go:164] failed to install plugin "sick-pods": plugin "sick-pods" does not offer installation for this platform
F0829 14:04:43.859067   12900 root.go:79] failed to install some plugins: [sick-pods]: plugin "sick-pods" does not offer installation for this platform
```

### PR DESCRIPTION
**Pull request by sammcj**
fixes #5

### CODE REVIEW

**Comment by alecjacobs5401** [comment]
@sammcj Thanks for opening this PR!

There are a few more steps necessary to get this working and listed in `krew`, but you should be able to do a manual build for your purposes until then. I'll have to re-familiarize myself with the `krew` workings, but it might be as simple as updating the [.krew.yaml](https://github.com/alecjacobs5401/kubectl-sick-pods/blob/master/.krew.yaml) file. I can take that on to try and move it forward

**Comment by alecjacobs5401** [comment]
Merged in #7

**Comment by alecjacobs5401** [comment]
@sammcj FYI - The PR is open to add the new version to `krew`, so that may be a bit before it is approved and merged and available for public download. Until then, you should be able to download the binary directly from the [release](https://github.com/alecjacobs5401/kubectl-sick-pods/releases/tag/v0.3.0)

**Comment by alecjacobs5401** [comment]
@sammcj [`krew` has approved/merged the PR](https://github.com/kubernetes-sigs/krew-index/pull/1499).

This is now available to install via `krew`

**Comment by sammcj** [comment]
Thank you!

**Pull request closed without merging**
